# Generated by Django 3.2.16 on 2022-11-20 16:27

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0176_merge_20221007_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTagProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttagsproduct', to='product.product')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttags', to='product.producttag')),
            ],
            options={
                'unique_together': {('product_tag', 'product')},
            },
        ),
        migrations.AddField(
            model_name='producttag',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='producttags', through='product.ProductTagProduct', to='product.Product'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['private_metadata'], name='producttag_p_meta_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='producttag_meta_idx'),
        ),
    ]
